quarkus.http.port=8081

quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=${DB_URL}
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}

quarkus.hibernate-orm.database.generation=validate
quarkus.hibernate-orm.log.sql=true